FROM debian:latest
MAINTAINER Kohei Yoshikawa <marimo3418@neko2.net>
# 2021.03.23 Updated
WORKDIR /opt
RUN apt update \
    && apt upgrade -y \
    && apt install git build-essential python3.7 -y
CMD sleep infinity
